const data = [
  {
    district: "Muzaffarnagar",
    role: "Super Visor",
    company: "Disha Industries",
    address: "Phase 2 road, Muzaffarnagar",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "Matric",
  },
  {
    district: "Muzaffarnagar",
    role: "Sales Man",
    company: "Kayna Healthcare",
    address: "Mahaveer Chowk, Muzaffarnagar",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "8th",
  },
  {
    district: "Muzaffarnagar",
    role: "Designer",
    company: "Dream Industries",
    address: "Shivpuri ,New Mandi, Muzaffarnagar",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "Gradute",
  },
  {
    district: "Muzaffarnagar",
    role: "Manager",
    company: "Aggarwal Duplex Board Mills Ltd.",
    address: "Bhopa Road, Muzaffarnagar",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "Graduate",
  },
  {
    district: "Shamli",
    role: "Site Manager",
    company: "Arpan Township Shamli",
    address: "MZN Road, Shamli",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "8th",
  },
  {
    district: "Shamli",
    role: "Engineer",
    company: "J.S. Jain Agro Indrusties (P) Ltd.",
    address: "Muzaffarnagar Road, Shamli",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "Graduate",
  },
  {
    district: "Shamli",
    role: "Salesman",
    company: "J.S. Jain Agro Indrusties (P) Ltd.",
    address: "Haaji Colony, Shamli",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 12,
    education: "8th",
  },
  {
    district: "Shamli",
    role: "Accountant",
    company: "Jitendra Electric Company",
    address: "Merut Karnal Road, Shamli",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 6,
    education: "Graduate",
  },
  {
    district: "Shamli",
    role: "Financial Advisory",
    company: "Bajaj Capital",
    address: "Merut Main Road, Shamli",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 6,
    education: "Matric",
  },
  {
    district: "Saharanpur",
    role: "Delivery Associate",
    company: "LocalMart",
    address: "22, Circular Road, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 10,
    education: "8th",
  },
  {
    district: "Saharanpur",
    role: "Sales Executive",
    company: "Saharanpur Electronics",
    address: "Shop No. 12, Main Market, Sarai Road, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 3,
    education: "8th",
  },
  {
    district: "Saharanpur",
    role: "Accountant",
    company: "Mittal & Sons Finance",
    address: "15/A, Gandhi Chowk, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 1,
    education: "Matric",
  },
  {
    district: "Saharanpur",
    role: "Data Entry Operator",
    company: "ABC Solutions",
    address: "Plot No. 101, Industrial Area, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "8th Pass",
  },
  {
    district: "Saharanpur",
    role: "Office Assistant",
    company: "Sharma Enterprises",
    address: "56, Nehru Colony, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "Graduate",
  },
  {
    district: "Saharanpur",
    role: "Field Sales Manager",
    company: "Gupta Agro Products",
    address: "19, Agriculture Market, Nakur, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 8,
    education: "Graduate",
  },
  {
    district: "Saharanpur",
    role: "Graphic Designer",
    company: "Creative Studio",
    address: "2nd Floor, City Center Mall, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "Graduate",
  },
  {
    district: "Saharanpur",
    role: "Receptionist",
    company: "City Hospital",
    address: "21/B, Civil Lines, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "8th",
  },
  {
    district: "Saharanpur",
    role: "Customer Support Rep",
    company: "CallHub Services",
    address: "45, IT Park, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 6,
    education: "8th",
  },
  {
    district: "Saharanpur",
    role: "Teacher",
    company: "Shishu Mandir School",
    address: "Plot No. 5, Shastri Nagar, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 3,
    education: "Matric",
  },
  {
    district: "Saharanpur",
    role: "Marketing Executive",
    company: "Jindal Pvt. Ltd.",
    address: "Industrial Estate, Rampur Road, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 3,
    education: "Graduate",
  },
  {
    district: "Saharanpur",
    role: "Software Engineer",
    company: "Tech Solutions",
    address: "Sector 10, Industrial Area, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 5,
    education: "Graduate",
  },
  {
    district: "Saharanpur",
    role: "Sales Executive",
    company: "Electronics Mart",
    address: "Main Market, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 3,
    education: "Matric",
  },
  {
    district: "Saharanpur",
    role: "Teacher",
    company: "Global School",
    address: "Civil Lines, Saharanpur",
    phone: "8791160360",
    whatsapp: "8791160360",
    openings: 2,
    education: "Graduate",
  },
];

export default data;
